language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "i8/FJASz3LmcQiBgkNGRWCVoZl9PYY7/S+Lkt+Ao6Xch6rsJlzEezRTGH/Rmw8+lKXhUld1TVZmC5iCgL48xQep9Zw+e7iBv+DQyPV8rjre3dAryfU8lAm7YAzpt2DyfnUnMnoIlxKUq9RlrPS4dYcFQ4WQQI+Ro8brB3U/cXU6TibP41ZVs3wUz4jmYEKWJr5CGwJwcCLFF7E1CF/jZAIyZjMyTRoskoVDt+p3bUUg8KRf4s6UhURoUY2nHAGaoxjOIrsZfEqmi4LalhsRlUvFsp1D2s4x4tl/bBqFDmxT4XAD+4kJK6Ctmc6kyJLQK854rzPGOCFQ7oLqItg6MYa/vBg5NjhLNsSLXuCdceT3jteTmES2MxUgD7JGuobXKdr/5THJNCe3TyuHRWqrgmkMCFdS7mF0BsUil8Q0AOQJS52isQeKhcnd2FxWuHP/0Np3VGxlMk95+Zmemm+rJTwI1Zn8rI+EeHtustbGnhW93L7YEVkwoTwXItqTSEjpqvFg+t3w4YNSt6RE4X4LcG3/+6ZdRv2WOHccpbz4jZn21mGVBrgp+JtnHRNJR5ipwzXsn6KurpyoGm954Iwdq4PC4QQYXfDvVPURSFU7wE7s0/35Xt312naguu8MOW/ZTHUV+uSfazqEE5AIBpWaQw0Un7+ou+FwZyJq2WyoeqQ8="
